name: DEV ADF to PROD ADF
on:
  workflow_dispatch:
env:
  rg-name: "pactiv-demo"
  adf-name: "dev-adf-ci-001"
  target-adf: "prod-adf-ci-001"
  
permissions:
  id-token: write
  contents: write
  actions: read
jobs:
  build:
    runs-on: ubuntu-24.04
    environment: DEV
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS}}
 
      - name: Set Azure subscription
        run: |
          az account set --subscription "${{ secrets.SUBSCRIPTION_ID}}"
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: install ADF Utilities package
        run: npm install
        working-directory: ${{github.workspace}}/
          
      - name: Clean install dependencies
        run: npm ci
        working-directory: ${{github.workspace}}
        
      - name: Validate
        run: npm run build validate ${{github.workspace}}/ /subscriptions/${{ secrets.SUBSCRIPTION_ID}}/resourceGroups/${{ env.rg-name}}/providers/Microsoft.DataFactory/factories/${{ env.adf-name}}
        working-directory: ${{github.workspace}}
        
      - name: Validate and Generate ARM template
        run: npm run build export ${{github.workspace}}/ /subscriptions/${{ secrets.SUBSCRIPTION_ID}}/resourceGroups/${{ env.rg-name}}/providers/Microsoft.DataFactory/factories/${{ env.adf-name}} "ExportedArmTemplate"
        working-directory: ${{github.workspace}}
        
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          find ${{github.workspace}}/ -name "*.json" -o -name "*.ps1" | while read file; do git add "$file"; done
          git commit -m "Update ARM templates [skip ci]" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      
      - name: Upload Exported ARM Template
        uses: actions/upload-artifact@v4
        with:
          name: ExportedArmTemplate
          path: ${{github.workspace}}/ExportedArmTemplate/      
  
  release:
    needs: build
    runs-on: ubuntu-24.04
    environment: DEV
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ExportedArmTemplate
      
      - name: Login via Az module
        uses: Azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: data-factory-deploy
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ env.rg-name}}
          dataFactoryName: ${{ env.target-adf}}
          armTemplateFile: ARMTemplateForFactory.json
          armTemplateParametersFile: ARMTemplateParametersForFactory.json
